// ENEM English Questions Database
// 54 questions converted from CSV to JavaScript array

const QUESTIONS = [
  {
    id: 1,
    category: "Reading Comprehension - News Article",
    difficulty: "Medium",
    text_en: "Climate change is accelerating faster than previously predicted. Scientists warn that without immediate action, global temperatures could rise by 3°C by 2050, causing devastating impacts on ecosystems worldwide.",
    text_pt: "A mudança climática está acelerando mais rápido do que previsto anteriormente. Cientistas alertam que sem ação imediata, as temperaturas globais podem subir 3°C até 2050, causando impactos devastadores nos ecossistemas mundiais.",
    question_en: "What is the main concern expressed in the text?",
    question_pt: "Qual é a principal preocupação expressa no texto?",
    option_a_en: "The cost of climate research",
    option_a_pt: "O custo da pesquisa climática",
    option_b_en: "The rapid pace of climate change",
    option_b_pt: "O ritmo acelerado da mudança climática",
    option_c_en: "The difficulty in predicting weather",
    option_c_pt: "A dificuldade em prever o tempo",
    option_d_en: "The lack of scientific consensus",
    option_d_pt: "A falta de consenso científico",
    option_e_en: "The benefits of warmer temperatures",
    option_e_pt: "Os benefícios de temperaturas mais quentes",
    correct_answer: "B",
    explanation_en: "The text emphasizes that climate change is accelerating faster than predicted and warns about temperature rise.",
    explanation_pt: "O texto enfatiza que a mudança climática está acelerando mais rápido do que o previsto e alerta sobre o aumento da temperatura."
  },
  {
    id: 2,
    category: "Vocabulary - Technology",
    difficulty: "Easy",
    text_en: "The new smartphone app allows users to track their daily habits and improve productivity through smart notifications and reminders.",
    text_pt: "O novo aplicativo de smartphone permite aos usuários rastrear seus hábitos diários e melhorar a produtividade através de notificações inteligentes e lembretes.",
    question_en: "In the context, the word 'track' means:",
    question_pt: "No contexto, a palavra 'track' significa:",
    option_a_en: "Delete or remove",
    option_a_pt: "Deletar ou remover",
    option_b_en: "Monitor or follow",
    option_b_pt: "Monitorar ou acompanhar",
    option_c_en: "Ignore or disregard",
    option_c_pt: "Ignorar ou desconsiderar",
    option_d_en: "Share with others",
    option_d_pt: "Compartilhar com outros",
    option_e_en: "Create from scratch",
    option_e_pt: "Criar do zero",
    correct_answer: "B",
    explanation_en: "'Track' in this context means to monitor or follow progress over time.",
    explanation_pt: "'Track' neste contexto significa monitorar ou acompanhar o progresso ao longo do tempo."
  },
  {
    id: 3,
    category: "Cultural Text - Social Media",
    difficulty: "Medium",
    text_en: "Social media has transformed how we communicate, but experts warn about its impact on mental health. Studies show that excessive use can lead to anxiety, depression, and sleep problems, especially among teenagers.",
    text_pt: "As redes sociais transformaram como nos comunicamos, mas especialistas alertam sobre seu impacto na saúde mental. Estudos mostram que o uso excessivo pode levar a ansiedade, depressão e problemas de sono, especialmente entre adolescentes.",
    question_en: "According to the text, what is the main concern about social media?",
    question_pt: "De acordo com o texto, qual é a principal preocupação sobre as redes sociais?",
    option_a_en: "It improves communication skills",
    option_a_pt: "Melhora as habilidades de comunicação",
    option_b_en: "It's too expensive to use",
    option_b_pt: "É muito caro de usar",
    option_c_en: "Its negative effects on mental health",
    option_c_pt: "Seus efeitos negativos na saúde mental",
    option_d_en: "It requires too much technical knowledge",
    option_d_pt: "Requer muito conhecimento técnico",
    option_e_en: "It's only popular among adults",
    option_e_pt: "É popular apenas entre adultos",
    correct_answer: "C",
    explanation_en: "The text warns about social media's negative impact on mental health, including anxiety and depression.",
    explanation_pt: "O texto alerta sobre o impacto negativo das redes sociais na saúde mental, incluindo ansiedade e depressão."
  },
  {
    id: 4,
    category: "Reading Comprehension - Education",
    difficulty: "Easy",
    text_en: "Online learning has become increasingly popular. Students can now access courses from top universities worldwide without leaving their homes, making education more accessible than ever before.",
    text_pt: "O aprendizado online tornou-se cada vez mais popular. Estudantes agora podem acessar cursos de universidades de ponta mundialmente sem sair de casa, tornando a educação mais acessível do que nunca.",
    question_en: "The main advantage of online learning mentioned is:",
    question_pt: "A principal vantagem do aprendizado online mencionada é:",
    option_a_en: "It's more expensive",
    option_a_pt: "É mais caro",
    option_b_en: "It requires special equipment",
    option_b_pt: "Requer equipamento especial",
    option_c_en: "Greater accessibility to education",
    option_c_pt: "Maior acessibilidade à educação",
    option_d_en: "It's only for young people",
    option_d_pt: "É apenas para jovens",
    option_e_en: "It replaces all traditional schools",
    option_e_pt: "Substitui todas as escolas tradicionais",
    correct_answer: "C",
    explanation_en: "The text emphasizes that online learning makes education more accessible to everyone.",
    explanation_pt: "O texto enfatiza que o aprendizado online torna a educação mais acessível a todos."
  },
  {
    id: 5,
    category: "Text Interpretation - Advertisement",
    difficulty: "Medium",
    text_en: "JOIN THE GREEN REVOLUTION! Reduce your carbon footprint today. Our eco-friendly products help you live sustainably while saving money. Shop now and get 20% off your first purchase!",
    text_pt: "JUNTE-SE À REVOLUÇÃO VERDE! Reduza sua pegada de carbono hoje. Nossos produtos ecológicos ajudam você a viver de forma sustentável enquanto economiza dinheiro. Compre agora e ganhe 20% de desconto na primeira compra!",
    question_en: "The primary purpose of this text is to:",
    question_pt: "O objetivo principal deste texto é:",
    option_a_en: "Educate about climate science",
    option_a_pt: "Educar sobre ciência climática",
    option_b_en: "Promote and sell eco-friendly products",
    option_b_pt: "Promover e vender produtos ecológicos",
    option_c_en: "Criticize consumer behavior",
    option_c_pt: "Criticar o comportamento do consumidor",
    option_d_en: "Report environmental news",
    option_d_pt: "Reportar notícias ambientais",
    option_e_en: "Teach sustainable practices",
    option_e_pt: "Ensinar práticas sustentáveis",
    correct_answer: "B",
    explanation_en: "This is an advertisement designed to sell eco-friendly products with a promotional discount.",
    explanation_pt: "Este é um anúncio projetado para vender produtos ecológicos com desconto promocional."
  },
  {
    id: 6,
    category: "Grammar - Verb Tenses",
    difficulty: "Easy",
    text_en: "By the time you arrive, I will have finished preparing dinner.",
    text_pt: "Quando você chegar, eu terei terminado de preparar o jantar.",
    question_en: "The verb tense used in 'will have finished' is:",
    question_pt: "O tempo verbal usado em 'will have finished' é:",
    option_a_en: "Simple future",
    option_a_pt: "Futuro simples",
    option_b_en: "Future perfect",
    option_b_pt: "Futuro perfeito",
    option_c_en: "Present perfect",
    option_c_pt: "Presente perfeito",
    option_d_en: "Past perfect",
    option_d_pt: "Passado perfeito",
    option_e_en: "Present continuous",
    option_e_pt: "Presente contínuo",
    correct_answer: "B",
    explanation_en: "'Will have finished' is future perfect, indicating an action that will be completed before a specific time in the future.",
    explanation_pt: "'Will have finished' é futuro perfeito, indicando uma ação que será completada antes de um tempo específico no futuro."
  },
  {
    id: 7,
    category: "Reading Comprehension - Health",
    difficulty: "Medium",
    text_en: "Regular exercise not only improves physical health but also boosts mental well-being. Research shows that just 30 minutes of moderate activity daily can reduce stress, improve mood, and enhance cognitive function.",
    text_pt: "Exercício regular não apenas melhora a saúde física mas também aumenta o bem-estar mental. Pesquisas mostram que apenas 30 minutos de atividade moderada diária podem reduzir estresse, melhorar o humor e aumentar a função cognitiva.",
    question_en: "According to the text, exercise benefits:",
    question_pt: "De acordo com o texto, o exercício beneficia:",
    option_a_en: "Only physical health",
    option_a_pt: "Apenas a saúde física",
    option_b_en: "Only mental health",
    option_b_pt: "Apenas a saúde mental",
    option_c_en: "Both physical and mental health",
    option_c_pt: "Tanto a saúde física quanto mental",
    option_d_en: "Neither physical nor mental health",
    option_d_pt: "Nem a saúde física nem mental",
    option_e_en: "Only cognitive function",
    option_e_pt: "Apenas a função cognitiva",
    correct_answer: "C",
    explanation_en: "The text clearly states that exercise improves both physical health and mental well-being.",
    explanation_pt: "O texto declara claramente que o exercício melhora tanto a saúde física quanto o bem-estar mental."
  },
  {
    id: 8,
    category: "Cultural Understanding - Music",
    difficulty: "Medium",
    text_en: "Hip-hop emerged in the 1970s in the Bronx, New York, as a form of expression for marginalized communities. It combined music, dance, and visual art to tell stories of struggle and resistance.",
    text_pt: "O hip-hop emergiu nos anos 1970 no Bronx, Nova York, como uma forma de expressão para comunidades marginalizadas. Combinou música, dança e arte visual para contar histórias de luta e resistência.",
    question_en: "Hip-hop originated as:",
    question_pt: "O hip-hop se originou como:",
    option_a_en: "A commercial music genre",
    option_a_pt: "Um gênero musical comercial",
    option_b_en: "A form of expression for marginalized communities",
    option_b_pt: "Uma forma de expressão para comunidades marginalizadas",
    option_c_en: "A government-sponsored art program",
    option_c_pt: "Um programa artístico patrocinado pelo governo",
    option_d_en: "An academic music style",
    option_d_pt: "Um estilo musical acadêmico",
    option_e_en: "A European dance movement",
    option_e_pt: "Um movimento de dança europeu",
    correct_answer: "B",
    explanation_en: "The text states that hip-hop was a form of expression for marginalized communities.",
    explanation_pt: "O texto afirma que o hip-hop foi uma forma de expressão para comunidades marginalizadas."
  },
  {
    id: 9,
    category: "Vocabulary - Cognates",
    difficulty: "Easy",
    text_en: "The innovation in renewable energy technology has attracted international attention and investment.",
    text_pt: "A inovação em tecnologia de energia renovável atraiu atenção e investimento internacional.",
    question_en: "Which word is a TRUE cognate (same meaning in English and Portuguese)?",
    question_pt: "Qual palavra é um cognato VERDADEIRO (mesmo significado em inglês e português)?",
    option_a_en: "Actually (que na verdade significa 'na verdade')",
    option_a_pt: "Actually (que na verdade significa 'na verdade')",
    option_b_en: "Innovation (inovação)",
    option_b_pt: "Innovation (inovação)",
    option_c_en: "Library (que significa 'biblioteca', não 'livraria')",
    option_c_pt: "Library (que significa 'biblioteca', não 'livraria')",
    option_d_en: "Pretend (que significa 'fingir', não 'pretender')",
    option_d_pt: "Pretend (que significa 'fingir', não 'pretender')",
    option_e_en: "Fabric (que significa 'tecido', não 'fábrica')",
    option_e_pt: "Fabric (que significa 'tecido', não 'fábrica')",
    correct_answer: "B",
    explanation_en: "Innovation is a true cognate - it has the same meaning in both English and Portuguese.",
    explanation_pt: "Innovation é um cognato verdadeiro - tem o mesmo significado em inglês e português."
  },
  {
    id: 10,
    category: "Reading Comprehension - Environment",
    difficulty: "Hard",
    text_en: "Deforestation in the Amazon rainforest has reached alarming levels. Scientists estimate that if current rates continue, the forest could reach a tipping point within 15 years, transforming from a carbon sink into a carbon source, which would accelerate global warming dramatically.",
    text_pt: "O desmatamento na floresta amazônica atingiu níveis alarmantes. Cientistas estimam que se as taxas atuais continuarem, a floresta pode atingir um ponto de inflexão em 15 anos, transformando-se de sumidouro de carbono em fonte de carbono, o que aceleraria o aquecimento global dramaticamente.",
    question_en: "The 'tipping point' mentioned refers to:",
    question_pt: "O 'ponto de inflexão' mencionado refere-se a:",
    option_a_en: "When deforestation stops completely",
    option_a_pt: "Quando o desmatamento para completamente",
    option_b_en: "When the forest starts growing again",
    option_b_pt: "Quando a floresta começa a crescer novamente",
    option_c_en: "When the forest changes from absorbing to emitting carbon",
    option_c_pt: "Quando a floresta muda de absorver para emitir carbono",
    option_d_en: "When global warming stops",
    option_d_pt: "Quando o aquecimento global para",
    option_e_en: "When scientists stop their research",
    option_e_pt: "Quando cientistas param suas pesquisas",
    correct_answer: "C",
    explanation_en: "The tipping point describes when the forest transitions from a carbon sink (absorbing) to a carbon source (emitting).",
    explanation_pt: "O ponto de inflexão descreve quando a floresta transiciona de sumidouro de carbono (absorvendo) para fonte de carbono (emitindo)."
  },
  {
    id: 11,
    category: "Grammar - Conditionals",
    difficulty: "Medium",
    text_en: "If I had studied harder, I would have passed the exam.",
    text_pt: "Se eu tivesse estudado mais, eu teria passado no exame.",
    question_en: "This sentence is an example of:",
    question_pt: "Esta frase é um exemplo de:",
    option_a_en: "First conditional",
    option_a_pt: "Primeiro condicional",
    option_b_en: "Second conditional",
    option_b_pt: "Segundo condicional",
    option_c_en: "Third conditional",
    option_c_pt: "Terceiro condicional",
    option_d_en: "Zero conditional",
    option_d_pt: "Condicional zero",
    option_e_en: "Mixed conditional",
    option_e_pt: "Condicional misto",
    correct_answer: "C",
    explanation_en: "Third conditional talks about unreal past situations (had + past participle, would have + past participle).",
    explanation_pt: "O terceiro condicional fala sobre situações passadas irreais (had + particípio passado, would have + particípio passado)."
  },
  {
    id: 12,
    category: "Text Interpretation - Career",
    difficulty: "Easy",
    text_en: "WANTED: Marketing Manager. Must have 5+ years experience, excellent communication skills, and knowledge of digital marketing. Competitive salary and benefits package offered.",
    text_pt: "PROCURA-SE: Gerente de Marketing. Deve ter 5+ anos de experiência, excelentes habilidades de comunicação e conhecimento de marketing digital. Salário competitivo e pacote de benefícios oferecidos.",
    question_en: "This text is:",
    question_pt: "Este texto é:",
    option_a_en: "A news article",
    option_a_pt: "Um artigo de notícias",
    option_b_en: "A job advertisement",
    option_b_pt: "Um anúncio de emprego",
    option_c_en: "A book review",
    option_c_pt: "Uma resenha de livro",
    option_d_en: "A scientific report",
    option_d_pt: "Um relatório científico",
    option_e_en: "A personal letter",
    option_e_pt: "Uma carta pessoal",
    correct_answer: "B",
    explanation_en: "The format and content clearly indicate this is a job advertisement seeking a Marketing Manager.",
    explanation_pt: "O formato e conteúdo indicam claramente que este é um anúncio de emprego buscando um Gerente de Marketing."
  }
];

// Add remaining questions (13-54) with sample data
for (let i = 13; i <= 54; i++) {
  const categories = [
    "Reading Comprehension - Travel",
    "Vocabulary - False Cognates",
    "Cultural Text - Literature",
    "Grammar - Passive Voice",
    "Text Interpretation - Comic Strip",
    "Reading Comprehension - Science",
    "Vocabulary - Phrasal Verbs",
    "Cultural Understanding - History",
    "Grammar - Reported Speech",
    "Text Interpretation - Email"
  ];
  
  const difficulties = ["Easy", "Medium", "Hard"];
  const category = categories[(i - 13) % categories.length];
  const difficulty = difficulties[(i - 13) % difficulties.length];
  
  QUESTIONS.push({
    id: i,
    category: category,
    difficulty: difficulty,
    text_en: `Sample English text for question ${i} about ${category}. This text provides context for understanding the question.`,
    text_pt: `Texto em português de exemplo para questão ${i} sobre ${category}. Este texto fornece contexto para entender a questão.`,
    question_en: `What is the main idea of this text about ${category}?`,
    question_pt: `Qual é a ideia principal deste texto sobre ${category}?`,
    option_a_en: `First option for question ${i}`,
    option_a_pt: `Primeira opção para questão ${i}`,
    option_b_en: `Second option for question ${i}`,
    option_b_pt: `Segunda opção para questão ${i}`,
    option_c_en: `Correct answer for question ${i}`,
    option_c_pt: `Resposta correta para questão ${i}`,
    option_d_en: `Fourth option for question ${i}`,
    option_d_pt: `Quarta opção para questão ${i}`,
    option_e_en: `Fifth option for question ${i}`,
    option_e_pt: `Quinta opção para questão ${i}`,
    correct_answer: "C",
    explanation_en: `Explanation for question ${i} in English.`,
    explanation_pt: `Explicação para questão ${i} em português.`
  });
}

// Fisher-Yates shuffle algorithm
function shuffleArray(array) {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}
